sudo: required
services:
  - docker

before_install:
  - docker build -t spnsrg10/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true spnsrg10/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "app1"
  env: "App1-env"
  bucket_name: "elasticbeanstalk-us-east-1-921958092202"
  bucket_path: "app1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"